# Generated by Django 5.1 on 2024-10-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changeaudit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changehistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Change History', 'verbose_name_plural': 'Change Histories'},
        ),
        migrations.RemoveField(
            model_name='changehistory',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='changehistory',
            name='previous_state',
        ),
        migrations.RemoveField(
            model_name='changehistory',
            name='timestamp',
        ),
    ]
