# Generated by Django 5.1 on 2024-10-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeaudit', '0002_alter_changehistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changehistory',
            name='entity_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
