# Generated by Django 5.1 on 2024-10-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeaudit', '0003_alter_changehistory_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changehistory',
            name='entity_id',
            field=models.CharField(max_length=100),
        ),
    ]
