# Generated by Django 5.1 on 2024-09-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address_paymentmethod_user_delete_accounts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_access', models.CharField(max_length=5)),
                ('account_access', models.CharField(max_length=5)),
                ('payment_access', models.CharField(max_length=5)),
                ('order_access', models.CharField(max_length=5)),
                ('cart_access', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['-created_at'],
            },
        ),
    ]
