# Generated by Django 5.1 on 2024-09-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='account_access',
            field=models.CharField(choices=[('edit', 'Edit'), ('view', 'View'), ('create', 'Create')], default='view', max_length=10),
        ),
        migrations.AlterField(
            model_name='roles',
            name='cart_access',
            field=models.CharField(choices=[('edit', 'Edit'), ('view', 'View'), ('create', 'Create')], default='view', max_length=10),
        ),
        migrations.AlterField(
            model_name='roles',
            name='order_access',
            field=models.CharField(choices=[('edit', 'Edit'), ('view', 'View'), ('create', 'Create')], default='view', max_length=10),
        ),
        migrations.AlterField(
            model_name='roles',
            name='payment_access',
            field=models.CharField(choices=[('edit', 'Edit'), ('view', 'View'), ('create', 'Create')], default='view', max_length=10),
        ),
        migrations.AlterField(
            model_name='roles',
            name='product_access',
            field=models.CharField(choices=[('edit', 'Edit'), ('view', 'View'), ('create', 'Create')], default='view', max_length=10),
        ),
    ]
