# Generated by Django 5.1 on 2024-09-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_cart_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
