# Generated by Django 5.1 on 2024-12-22 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cart_changed_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
