# Generated by Django 5.1 on 2024-08-15 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('chipset', models.CharField(max_length=255)),
                ('socket', models.CharField(max_length=255)),
                ('form_factor', models.CharField(max_length=255)),
                ('memory_type', models.CharField(max_length=255)),
                ('max_capacity', models.CharField(max_length=255)),
                ('slots', models.CharField(max_length=255)),
                ('supported_speeds', models.CharField(max_length=255)),
                ('m2_slots', models.IntegerField()),
                ('sata_ports', models.IntegerField()),
                ('pcie_slots', models.CharField(max_length=255)),
                ('wired_lan', models.CharField(max_length=255)),
                ('wireless', models.CharField(max_length=255)),
                ('audio_codec', models.CharField(max_length=255)),
                ('channels', models.CharField(max_length=255)),
                ('usb_3_2_gen_2x2_type_c_ports', models.IntegerField()),
                ('usb_3_2_gen_2_type_a_ports', models.IntegerField()),
                ('usb_3_2_gen_1_type_a_ports', models.IntegerField()),
                ('usb_2_0_ports', models.IntegerField()),
                ('lan', models.CharField(max_length=255)),
                ('audio_jack', models.CharField(max_length=255)),
                ('clear_cmos_button', models.BooleanField(default=False)),
                ('usb_3_2_gen_1_headers', models.IntegerField()),
                ('usb_3_2_gen_2_header', models.IntegerField()),
                ('sata_headers', models.IntegerField()),
                ('m2_pcie_headers', models.IntegerField()),
                ('features', models.TextField()),
                ('compatibility', models.CharField(max_length=255)),
                ('warranty', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motherboards_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motherboards_created', to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(db_column='product_id', editable=False, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
