# Generated by Django 5.1 on 2024-09-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_motherboard_clear_cmos_button_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='db_table',
            field=models.CharField(default='', max_length=100),
        ),
    ]
