# Generated by Django 5.1 on 2024-09-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_db_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
