# Generated by Django 5.1 on 2024-09-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
