# Generated by Django 5.1 on 2024-12-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_category_changed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=100, unique=True)),
                ('field_name', models.CharField(max_length=100)),
                ('db_field_name', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=False)),
                ('access_levels', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('entity_name', 'field_name')},
            },
        ),
    ]
