# Generated by Django 5.1 on 2024-12-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_fieldconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldconfig',
            name='access_levels',
        ),
        migrations.AddField(
            model_name='fieldconfig',
            name='access_level',
            field=models.IntegerField(default=0),
        ),
    ]
