# Generated by Django 5.1 on 2024-12-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_fieldconfig_access_levels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldconfig',
            name='entity_name',
            field=models.CharField(max_length=100),
        ),
    ]
