# Generated by Django 5.1 on 2024-12-22 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_delete_cart'),
        ('products', '0015_alter_brand_changed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Motherboard',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
